services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
    command: server --console-address :9001 /data
    healthcheck:
      start_period: "500ms"
      start_interval: "200ms"
      interval: "10s"
      test: ["CMD", "curl", "-I", "http://minio:9000/minio/health/live"]

  create-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        mc config host add minio http://minio:9000 ${S3_ACCESS_KEY_ID} ${S3_SECRET_KEY};
        mc mb minio/${BUCKET_NAME} --ignore-existing;
        echo 'Bucket created successfully';
      "
